$(document).data('clips', {
    '0'          : ['0'],
    '1'          : ['1-1', '1-2', '1-3'],
    '10'         : ['A-1', 'A-2', 'A-3'],
    '2'          : ['2-1', '2-2'],
    '2s'         : ['2s-1', '2s-2'],
    '3'          : ['3-1', '3-2'],
    '4'          : ['4-1', '4-2'],
    '5'          : ['5-1', '5-2'],
    '6'          : ['6-1', '6-2'],
    '7'          : ['7-1', '7-2'],
    '8'          : ['8-1', '8-2'],
    '9'          : ['9-1', '9-2', '9-3'],
    'ahy'        : ['ahy'],
    'allare'     : ['allare-1', 'allare-2'],
    'already'    : ['already'],
    'am'         : ['am'],
    'and'        : ['and'],
    'at'         : ['at'],
    'attention'  : ['attention'],
    'ay'         : ['ay'],
    'bcjl'       : ['bcjl'],
    'beautiful'  : ['beautiful'],
    'because'    : ['because'],
    'become'     : ['become'],
    'bei'        : ['bei'],
    'bk'         : ['bk'],
    'bless'      : ['bless'],
    'bu'         : ['bu'],
    'buddy'      : ['buddy-1', 'buddy-2'],
    'burn'       : ['burn-1', 'burn-2'],
    'chok'       : ['chok'],
    'ck'         : ['ck'],
    'classmate'  : ['classmate'],
    'cloud'      : ['cloud'],
    'come'       : ['come'],
    'creativity' : ['creativity'],
    'czr'        : ['czr-1', 'czr-2', 'czr-3'],
    'day'        : ['day-1', 'day-2'],
    'de'         : ['de'],
    'dfsd'       : ['dfsd'],
    'di'         : ['di'],
    'diamond'    : ['diamond'],
    'dian'       : ['dian'],
    'different'  : ['different'],
    'dkhj'       : ['dkhj'],
    'dksl'       : ['dksl'],
    'donot'      : ['donot-1', 'donot-2'],
    'downside'   : ['downside'],
    'dx'         : ['dx'],
    'ec'         : ['ec'],
    'every'      : ['every'],
    'fen'        : ['fen'],
    'friend'     : ['friend'],
    'friendship' : ['friendship'],
    'gay'        : ['gay-1', 'gay-2', 'gay-3', 'gay-4'],
    'haha'       : ['haha'],
    'handle'     : ['handle'],
    'hao'        : ['hao'],
    'haveno'     : ['haveno'],
    'haveto'     : ['haveto-1', 'haveto-2'],
    'here'       : ['here'],
    'hhd'        : ['hhd-1', 'hhd-2'],
    'hole'       : ['hole'],
    'i'          : ['i'],
    'if'         : ['if'],
    'include'    : ['include'],
    'intimate'   : ['intimate'],
    'is'         : ['is'],
    'itsnot'     : ['itsnot'],
    'ji'         : ['ji'],
    'jie'        : ['jie'],
    'jzlmy'      : ['jzlmy'],
    'kd'         : ['kd'],
    'ke'         : ['ke-1', 'ke-2', 'ke-3'],
    'ldzy'       : ['ldzy'],
    'lift'       : ['lift-1', 'lift-2'],
    'listen'     : ['listen'],
    'long'       : ['long'],
    'love'       : ['love-1', 'love-2'],
    'lu'         : ['lu'],
    'ma'         : ['ma'],
    'mei'        : ['mei'],
    'mist'       : ['mist'],
    'moe'        : ['moe'],
    'momo'       : ['momo'],
    'ng'         : ['ng-1', 'ng-2'],
    'nohole'     : ['nohole'],
    'nong'       : ['nong'],
    'notbe'      : ['notbe'],
    'ohno'       : ['ohno'],
    'open'       : ['open'],
    'or'         : ['or'],
    'people'     : ['people'],
    'pm'         : ['pm'],
    'powerless'  : ['powerless'],
    'qjs'        : ['qjs'],
    'qs'         : ['qs'],
    'qsj'        : ['qsj'],
    'qz'         : ['qz-1', 'qz-2'],
    'relation'   : ['relation'],
    'release'    : ['release'],
    'save'       : ['save'],
    'sf'         : ['sf'],
    'share'      : ['share'],
    'somany'     : ['somany'],
    'sorry'      : ['sorry'],
    'sound'      : ['sound'],
    'start'      : ['start'],
    'thatis'     : ['thatis'],
    'thb'        : ['thb'],
    'then'       : ['then-1', 'then-2'],
    'this'       : ['this'],
    'tien'       : ['tien'],
    'today'      : ['today'],
    'total'      : ['total'],
    'uh'         : ['uh'],
    'use'        : ['use'],
    'very'       : ['very'],
    'wah'        : ['wah'],
    'we'         : ['we-1', 'we-2'],
    'wehaveto'   : ['wehaveto'],
    'where'      : ['where'],
    'whole'      : ['whole'],
    'why'        : ['why'],
    'wjjphqk'    : ['wjjphqk'],
    'wl'         : ['wl'],
    'wow'        : ['wow-1', 'wow-2'],
    'wrong'      : ['wrong'],
    'ws'         : ['ws'],
    'wts'        : ['wts'],
    'xiong'      : ['xiong'],
    'yang'       : ['yang'],
    'yesterday'  : ['yesterday'],
    'you'        : ['you-1', 'you-2'],
    'youhaveto'  : ['youhaveto'],
    'yousee'     : ['yousee'],
    'youseesee'  : ['youseesee'],
    'zd'         : ['zd'],
    'zrzd'       : ['zrzd'],
    'zs'         : ['zs'],
    'zui'        : ['zui'],
    'zy'         : ['zy'],
});
