$(document).data('clips', {
    '+00'        : ['mj/+00'],
    '+01'        : ['mj/+01'],
    '+01+'       : ['mj/+01+'],
    '+02'        : ['mj/+02'],
    '+02+'       : ['mj/+02+'],
    '+03'        : ['mj/+03'],
    '+04'        : ['mj/+04'],
    '+04+'       : ['mj/+04+'],
    '+05'        : ['mj/+05'],
    '+05+'       : ['mj/+05+'],
    '+06'        : ['mj/+06'],
    '+06+'       : ['mj/+06+'],
    '+07'        : ['mj/+07'],
    '+11'        : ['mj/+11'],
    '+11+'       : ['mj/+11+'],
    '+12'        : ['mj/+12'],
    '+12+'       : ['mj/+12+'],
    '+13'        : ['mj/+13'],
    '+14'        : ['mj/+14'],
    '+14+'       : ['mj/+14+'],
    '+15'        : ['mj/+15'],
    '+15+'       : ['mj/+15+'],
    '+16'        : ['mj/+16'],
    '+16+'       : ['mj/+16+'],
    '+17'        : ['mj/+17'],
    '+21'        : ['mj/+21'],
    '0'          : ['mj/0'],
    '1'          : ['mj/1-1', 'mj/1-2', 'mj/1-3'],
    '10'         : ['mj/A-1', 'mj/A-2', 'mj/A-3'],
    '2'          : ['mj/2-1', 'mj/2-2'],
    '2s'         : ['mj/2s-1', 'mj/2s-2'],
    '3'          : ['mj/3-1', 'mj/3-2'],
    '4'          : ['mj/4-1', 'mj/4-2'],
    '5'          : ['mj/5-1', 'mj/5-2'],
    '6'          : ['mj/6-1', 'mj/6-2'],
    '7'          : ['mj/7-1', 'mj/7-2'],
    '8'          : ['mj/8-1', 'mj/8-2'],
    '9'          : ['mj/9-1', 'mj/9-2', 'mj/9-3'],
    'ah'         : ['mj/ah'],
    'ahy'        : ['mj/ahy'],
    'allare'     : ['mj/allare-1', 'mj/allare-2'],
    'already'    : ['mj/already'],
    'am'         : ['mj/am'],
    'and'        : ['mj/and'],
    'annoy'      : ['mj/annoy'],
    'at'         : ['mj/at'],
    'attention'  : ['mj/attention'],
    'ay'         : ['mj/ay'],
    'bao'        : ['mj/bao'],
    'bcjl'       : ['mj/bcjl'],
    'beautiful'  : ['mj/beautiful'],
    'because'    : ['mj/because'],
    'become'     : ['mj/become'],
    'behind'     : ['mj/behind'],
    'bei'        : ['mj/bei'],
    'besides'    : ['mj/besides'],
    'bk'         : ['mj/bk'],
    'bless'      : ['mj/bless'],
    'bspnl'      : ['mj/bspnl'],
    'bu'         : ['mj/bu'],
    'buddy'      : ['mj/buddy-1', 'mj/buddy-2'],
    'burn'       : ['mj/burn-1', 'mj/burn-2'],
    'chok'       : ['mj/chok'],
    'ck'         : ['mj/ck'],
    'classmate'  : ['mj/classmate'],
    'cloud'      : ['mj/cloud'],
    'come'       : ['mj/come'],
    'creativity' : ['mj/creativity'],
    'czr'        : ['mj/czr-1', 'mj/czr-2', 'mj/czr-3'],
    'day'        : ['mj/day-1', 'mj/day-2'],
    'de'         : ['mj/de-1', 'mj/de-2'],
    'dfsd'       : ['mj/dfsd'],
    'di'         : ['mj/di'],
    'diamond'    : ['mj/diamond'],
    'dian'       : ['mj/dian'],
    'different'  : ['mj/different'],
    'dkhj'       : ['mj/dkhj'],
    'dksl'       : ['mj/dksl'],
    'donot'      : ['mj/donot-1', 'mj/donot-2'],
    'downside'   : ['mj/downside'],
    'drink'      : ['mj/drink-1', 'mj/drink-2'],
    'duo'        : ['mj/duo'],
    'dx'         : ['mj/dx'],
    'ec'         : ['mj/ec'],
    'effect'     : ['mj/effect'],
    'ei'         : ['mj/ei'],
    'eout'       : ['mj/eout-1', 'mj/eout-2'],
    'every'      : ['mj/every'],
    'fen'        : ['mj/fen'],
    'for'        : ['mj/for-1', 'mj/for-2'],
    'forgot'     : ['mj/forgot'],
    'friend'     : ['mj/friend'],
    'friendship' : ['mj/friendship'],
    'fs'         : ['mj/fs'],
    'gay'        : ['mj/gay-1', 'mj/gay-2', 'mj/gay-3', 'mj/gay-4'],
    'go'         : ['mj/go'],
    'guo'        : ['mj/guo'],
    'haha'       : ['mj/haha'],
    'handle'     : ['mj/handle'],
    'hao'        : ['mj/hao'],
    'haveno'     : ['mj/haveno'],
    'haveto'     : ['mj/haveto-1', 'mj/haveto-2'],
    'here'       : ['mj/here'],
    'hfs'        : ['mj/hfs'],
    'hhd'        : ['mj/hhd-1', 'mj/hhd-2'],
    'hole'       : ['mj/hole'],
    'i'          : ['mj/i'],
    'if'         : ['mj/if'],
    'in'         : ['mj/in'],
    'include'    : ['mj/include'],
    'intimate'   : ['mj/intimate'],
    'is'         : ['mj/is'],
    'itsnot'     : ['mj/itsnot'],
    'jc'         : ['mj/jc'],
    'jg'         : ['mj/jg'],
    'ji'         : ['mj/ji'],
    'jie'        : ['mj/jie'],
    'jiu'        : ['mj/jiu'],
    'jzlmy'      : ['mj/jzlmy'],
    'kd'         : ['mj/kd'],
    'ke'         : ['mj/ke-1', 'mj/ke-2', 'mj/ke-3'],
    'kw'         : ['mj/kw'],
    'ldzy'       : ['mj/ldzy'],
    'le'         : ['mj/le'],
    'lf'         : ['mj/lf'],
    'lift'       : ['mj/lift-1', 'mj/lift-2'],
    'line'       : ['mj/line'],
    'listen'     : ['mj/listen'],
    'long'       : ['mj/long'],
    'love'       : ['mj/love-1', 'mj/love-2'],
    'lq'         : ['mj/lq'],
    'lu'         : ['mj/lu'],
    'ma'         : ['mj/ma'],
    'mei'        : ['mj/mei'],
    'mist'       : ['mj/mist'],
    'mjx'        : ['mj/mjx'],
    'moe'        : ['mj/moe'],
    'momo'       : ['mj/momo'],
    'month'      : ['mj/month'],
    'ng'         : ['mj/ng-1', 'mj/ng-2'],
    'nnlynjanl'  : ['mj/nnlynjanl'],
    'nohole'     : ['mj/nohole'],
    'nong'       : ['mj/nong'],
    'notbe'      : ['mj/notbe'],
    'nowonder'   : ['mj/nowonder'],
    'often'      : ['mj/often'],
    'ohno'       : ['mj/ohno'],
    'oo'         : ['mj/oo'],
    'open'       : ['mj/open'],
    'or'         : ['mj/or'],
    'out'        : ['mj/out'],
    'pc'         : ['mj/pc'],
    'people'     : ['mj/people'],
    'please'     : ['mj/please'],
    'pm'         : ['mj/pm'],
    'powerless'  : ['mj/powerless'],
    'pullout'    : ['mj/pullout'],
    'putdown'    : ['mj/putdown'],
    'qjs'        : ['mj/qjs'],
    'qs'         : ['mj/qs'],
    'qsj'        : ['mj/qsj'],
    'qz'         : ['mj/qz-1', 'mj/qz-2'],
    'relation'   : ['mj/relation'],
    'release'    : ['mj/release'],
    'rightnow'   : ['mj/rightnow'],
    'save'       : ['mj/save'],
    'sbl'        : ['mj/sbl'],
    'see'        : ['mj/see'],
    'sf'         : ['mj/sf'],
    'share'      : ['mj/share'],
    'sheme'      : ['mj/sheme'],
    'shutdown'   : ['mj/shutdown'],
    'sick'       : ['mj/sick'],
    'so'         : ['mj/so'],
    'somany'     : ['mj/somany'],
    'sorry'      : ['mj/sorry'],
    'sound'      : ['mj/sound'],
    'start'      : ['mj/start'],
    'ta'         : ['mj/ta'],
    'thatis'     : ['mj/thatis'],
    'thb'        : ['mj/thb'],
    'then'       : ['mj/then-1', 'mj/then-2'],
    'they'       : ['mj/they'],
    'this'       : ['mj/this-1', 'mj/this-2'],
    'tien'       : ['mj/tien'],
    'tl'         : ['mj/tl'],
    'to'         : ['mj/to'],
    'today'      : ['mj/today'],
    'total'      : ['mj/total'],
    'tq'         : ['mj/tq-1', 'mj/tq-2'],
    'trick'      : ['mj/trick'],
    'uh'         : ['mj/uh'],
    'use'        : ['mj/use'],
    'very'       : ['mj/very'],
    'wah'        : ['mj/wah'],
    'wc'         : ['mj/wc'],
    'we'         : ['mj/we-1', 'mj/we-2'],
    'website'    : ['mj/website'],
    'wehaveto'   : ['mj/wehaveto'],
    'where'      : ['mj/where'],
    'whole'      : ['mj/whole'],
    'why'        : ['mj/why'],
    'with'       : ['mj/with-1', 'mj/with-2'],
    'wjjphqk'    : ['mj/wjjphqk'],
    'wl'         : ['mj/wl'],
    'wow'        : ['mj/wow-1', 'mj/wow-2'],
    'wrong'      : ['mj/wrong'],
    'ws'         : ['mj/ws'],
    'wts'        : ['mj/wts'],
    'xiong'      : ['mj/xiong'],
    'xl'         : ['mj/xl'],
    'xx'         : ['mj/xx'],
    'yang'       : ['mj/yang'],
    'yesterday'  : ['mj/yesterday'],
    'yjzk'       : ['mj/yjzk'],
    'you'        : ['mj/you-1', 'mj/you-2'],
    'youhaveto'  : ['mj/youhaveto'],
    'yousee'     : ['mj/yousee'],
    'youseesee'  : ['mj/youseesee'],
    'yrbdz'      : ['mj/yrbdz'],
    'yw'         : ['mj/yw'],
    'zd'         : ['mj/zd'],
    'zhe'        : ['mj/zhe-1', 'mj/zhe-2'],
    'zrzd'       : ['mj/zrzd'],
    'zs'         : ['mj/zs'],
    'zui'        : ['mj/zui'],
    'zy'         : ['mj/zy'],
    /* devotion */
    'd-1morep'   : ['devotion/1morep-1', 'devotion/1morep-2'],
    'd-84'       : ['devotion/84'],
    'd-85'       : ['devotion/85'],
    'd-86'       : ['devotion/86'],
    'd-87'       : ['devotion/87'],
    'd-88'       : ['devotion/88-1', 'devotion/88-2', 'devotion/88-3', 'devotion/88-4'],
    'd-8888'     : ['devotion/8888'],
    'd-anymore'  : ['devotion/anymore'],
    'd-more'     : ['devotion/more-1', 'devotion/more-2'],
    'd-hello'    : ['devotion/hello'],
    'd-mrdu'     : ['devotion/mrdu'],
    'd-iamho'    : ['devotion/iamho'],
    'd-serious'  : ['devotion/serious'],
    'd-sorry'    : ['devotion/sorry'],
    'd-notwork'  : ['devotion/notwork'],
    'd-nopanic'  : ['devotion/nopanic'],
    'd-zxcy'     : ['devotion/zxcy'],
    'd-irecord'  : ['devotion/irecord'],
    'd-xczl'     : ['devotion/xczl'],
    'd-ringing'  : ['devotion/ringing'],
    'd-qzdr'     : ['devotion/qzdr'],
    'd-zzqr'     : ['devotion/zzqr'],
    'd-belive'   : ['devotion/believe'],
    /* FA-DA-CAI */
    'h-choke'    : ['han/choke'],
    'h-eh'       : ['han/eh'],
    'h-must'     : ['han/must'],
    'h-3'        : ['han/3'],
    'h-up'       : ['han/up'],
    'h-down'     : ['han/down'],
    'h-sorry'    : ['han/sorry'],
    'h-donot'    : ['han/donot'],
    'h-byg'      : ['han/byg'],
    'h-arent'    : ['han/arent'],
    'h-le'       : ['han/le'],
    'h-he'       : ['han/he'],
    'h-but'      : ['han/but'],
    'h-who'      : ['han/who'],
    'h-like'     : ['han/like'],
    'h-first'    : ['han/first'],
    'h-gather'   : ['han/gather'],
    'h-labor'    : ['han/labor'],
    'h-10w'      : ['han/10w'],
    'h-ji'       : ['han/ji'],
    'h-though'   : ['han/though'],
    'h-maybe'    : ['han/maybe'],
    'h-du'       : ['han/du'],
    'h-sh'       : ['han/sh'],
    'h-at'       : ['han/at'],
    'h-big'      : ['han/big'],
    'h-too'      : ['han/too'],
    'h-hbh'      : ['han/hbh'],
    'h-noprob'   : ['han/noprob'],
    'h-shoot'    : ['han/shoot'],
    'h-dbd'      : ['han/dbd'],
    'h-small'    : ['han/small'],
    'h-xbs'      : ['han/xbs'],
    'h-fart'     : ['han/fart'],
    'h-ahole'    : ['han/ahole'],
    'h-shuai'    : ['han/shuai'],
    'h-rszq'     : ['han/rszq'],
    'h-fromback' : ['han/fromback'],
    'h-fast'     : ['han/fast'],
    'h-si'       : ['han/si-1', 'han/si-2'],
    'h-aybr'     : ['han/aybr'],
    'h-thanks'   : ['han/thanks'],
    'h-me'       : ['han/me'],
    'h-dontknow' : ['han/dontknow'],
    'h-we'       : ['han/we'],
    'h-ithink'   : ['han/ithink'],
    'h-ifeel'    : ['han/ifeel'],
    'h-nohelp'   : ['han/nohelp'],
    'h-accept'   : ['han/accept'],
    'h-gao'      : ['han/gao-1', 'han/gao-2'],
    'h-zheng'    : ['han/zheng'],
    'h-bijao'    : ['han/bijao'],
    'h-noprob'   : ['han/noprob'],
    'h-bath'     : ['han/bath'],
    'h-gee'      : ['han/gee'],
    'h-then'     : ['han/then'],
    'h-thenwhat' : ['han/thenwhat'],
    'h-smlfcl'   : ['han/smlfcl'],
    'h-fclyh'    : ['han/fclyh'],
    'h-de'       : ['han/de'],
    'h-kan'      : ['han/kan'],
    'h-hard'     : ['han/hard'],
    'h-stand'    : ['han/stand'],
    'h-wait'     : ['han/wait'],
    'h-jing'     : ['han/jing'],
    'h-teacher'  : ['han/teacher'],
    'h-fmore'    : ['han/fmore'],
    'h-comf'     : ['han/comf'],
    'h-act'      : ['han/act'],
    'h-serious'  : ['han/serious'],
    'h-say'      : ['han/say'],
    'h-sszd'     : ['han/sszd'],
    'h-hls'      : ['han/hls'],
    'h-let'      : ['han/let'],
    'h-fu'       : ['han/fu'],
    'h-soldier'  : ['han/soldier'],
    'h-jiao'     : ['han/jiao'],
    'h-hmfcl'    : ['han/hmfcl'],
    'h-na'       : ['han/na'],
    'h-allare'   : ['han/allare'],
    'h-allwill'  : ['han/allwill'],
    'h-dr'       : ['han/dr'],
    'h-sfcl'     : ['han/sfcl'],
    'h-point'    : ['han/point'],
    'h-long'     : ['han/long-1', 'han/long-2'],
    'h-ah'       : ['han/ah'],
    'h-fei'      : ['han/fei'],
    'h-very'     : ['han/very-1', 'han/very-2'],
    'h-veryimp'  : ['han/veryimp'],
    'h-gz'       : ['han/gz'],
});
